"""Build the quality-detection figure from the measured DQA scorecard."""

from __future__ import annotations

import matplotlib.pyplot as plt
import pandas as pd
from deck_style import AMBER, FIGURE_DIR, GREEN, INK, MIST, RED, ROOT, SLATE, setup
from matplotlib.patches import FancyBboxPatch


def main() -> None:
    setup()
    scorecard = pd.read_parquet(ROOT / "data/lakehouse/gold/gold_dqa_scorecard.parquet")
    injected = int(scorecard["injected_count"].sum())
    detected = int(scorecard["detected_count"].sum())
    missed = int(scorecard["missed_count"].sum())
    false_positives = int(scorecard["false_positive_count"].sum())
    rate = detected / injected

    fig, ax = plt.subplots(figsize=(13.333, 5.7))
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 10)
    ax.axis("off")

    ax.add_patch(
        FancyBboxPatch(
            (4, 4.2),
            92,
            1.55,
            boxstyle="round,pad=0.03,rounding_size=0.28",
            facecolor=MIST,
            edgecolor="none",
        )
    )
    ax.add_patch(
        FancyBboxPatch(
            (4, 4.2),
            92 * rate,
            1.55,
            boxstyle="round,pad=0.03,rounding_size=0.28",
            facecolor=GREEN,
            edgecolor="none",
        )
    )
    ax.text(
        5.5, 4.96, f"{detected:,} detected", color="white", fontsize=18, weight="bold", va="center"
    )
    ax.annotate(
        f"{missed:,} missed",
        xy=(96, 5.0),
        xytext=(97.5, 6.45),
        arrowprops={"arrowstyle": "-", "color": RED, "lw": 1.6},
        color=RED,
        fontsize=13,
        weight="bold",
        ha="right",
    )

    ax.text(4, 8.35, f"{rate:.2%}", fontsize=40, weight="bold", color=INK)
    ax.text(4, 7.65, "of deliberately planted defects were found", fontsize=18, color=SLATE)

    cards = [
        (4, f"{len(scorecard)}", "quality rules ran", AMBER),
        (35.5, f"{injected:,}", "known defects planted", RED),
        (67, f"{false_positives:,}", "extra flags for review", SLATE),
    ]
    for x, number, label, color in cards:
        ax.text(x, 2.45, number, fontsize=23, weight="bold", color=color)
        ax.text(x, 1.8, label, fontsize=13, color=SLATE)

    ax.text(
        4,
        0.65,
        "Synthetic proof case · fixed seed · scorecard generated by the pipeline",
        fontsize=11.5,
        color=SLATE,
    )
    out = FIGURE_DIR / "quality_detection.pdf"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    print(out)


if __name__ == "__main__":
    main()
